--------------------------------------------------------
--  File created - poniedziałek-czerwca-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHD_DEF_PRACY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_DEF_PRACY" 
   (	"ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"NORMA_MIN_H" NUMBER, 
	"NORMA_MAX_H" NUMBER, 
	"KOSZT_JEDN_PRACY" NUMBER, 
	"CHD_ID_DEF_PRACY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_DEF_PRACY_KEY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_DEF_PRACY_KEY" 
   (	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(100 BYTE), 
	"ZRODLO_DANYCH" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_DEF_ZUZYCIA
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_DEF_ZUZYCIA" 
   (	"ID_DEF_ZUZYCIA" VARCHAR2(20 BYTE), 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"CHD_ID_DEF_PRACY" NUMBER, 
	"CHD_ID_MATERIALU" NUMBER, 
	"CHD_ID_DEF_ZUZYCIA" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_DEF_ZUZYCIA_KEY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_DEF_ZUZYCIA_KEY" 
   (	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(100 BYTE), 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"ZRODLO_DANYCH" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_MATERIAL
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_MATERIAL" 
   (	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"KOSZT_JEDN" NUMBER, 
	"CHD_ID_MATERIALU" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_MATERIAL_KEY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_MATERIAL_KEY" 
   (	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"ZRODLO_DANYCH" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_PRACA
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_PRACA" 
   (	"ID_PRACY" NUMBER, 
	"CHD_ID_PRACOWNIKA" NUMBER, 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"CHD_ID_DEF_PRACY" NUMBER, 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"CHD_ID_MATERIALU" NUMBER, 
	"ILOSC_MATERIALU" NUMBER, 
	"CHD_ID_PRACY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_PRACA_KEY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_PRACA_KEY" 
   (	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(100 BYTE), 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_PRACOWNIK
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_PRACOWNIK" 
   (	"IMIE_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"NAZWISKO_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"CHD_ID_PRACOWNIKA" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CHD_PRACOWNIK_KEY
--------------------------------------------------------

  CREATE TABLE "HD2018"."CHD_PRACOWNIK_KEY" 
   (	"CHD_ID_DEF_PRACY" NUMBER, 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table META_DATA
--------------------------------------------------------

  CREATE TABLE "HD2018"."META_DATA" 
   (	"NAZWA" VARCHAR2(20 BYTE), 
	"NUMER_OST_ZAL_PRZYROSTU" NUMBER,
	"NUMER_OST_PRZYROSTU" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_DEF_PRACY
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_DEF_PRACY" 
   (	
      "ID_DEF_PRACY" NUMBER, 
      "NAZWA_PRACY" VARCHAR2(100 BYTE), 
      "JEDNOSTKA" VARCHAR2(100 BYTE), 
      "NORMA_MIN_H" NUMBER, 
      "NORMA_MAX_H" NUMBER, 
      "KOSZT_JEDN_PRACY" NUMBER, 
      "USUNIETY" NUMBER,

      "ZRODLO_DANYCH" NUMBER, 
      "NUMER_PRZYROSTU" NUMBER, 

   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;

-------------------------------------------------
--  DDL for Table STG_DEF_PRACY_EXT
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_DEF_PRACY_EXT" 
   (
      "ID_DEF_PRACY" NUMBER, 
      "NAZWA_PRACY" VARCHAR2(100 BYTE), 
      "JEDNOSTKA" VARCHAR2(100 BYTE), 
      "NORMA_MIN_H" NUMBER, 
      "NORMA_MAX_H" NUMBER, 
      "KOSZT_JEDN_PRACY" NUMBER, 
      "USUNIETY" NUMBER,
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXTERNAL_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
        (
        ID_DEF_PRACY,NAZWA_PRACY,JEDNOSTKA,NORMA_MIN_H,NORMA_MAX_H,KOSZT_JEDN_PRACY,USUNIETY
        )
        )
      LOCATION
       ( 'DEF_PRACY.csv'
       )
    );
--------------------------------------------------------
--  DDL for Table STG_DEF_ZUZYCIA
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_DEF_ZUZYCIA" 
   (	"ID_DEF_ZUZYCIA" NUMBER, 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_DEF_ZUZYCIA_D
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_DEF_ZUZYCIA_D" 
   (	"ID_DEF_ZUZYCIA" NUMBER, 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_DEF_ZUZYCIA_EXT
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_DEF_ZUZYCIA_EXT" 
   (	"ID_DEF_ZUZYCIA" NUMBER, 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXTERNAL_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
        (
        ID_DEF_ZUZYCIA,NORMA_MIN_JEDN,NORMA_MAX_JEDN,NAZWA_PRACY,NAZWA_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU
        )
        )
      LOCATION
       ( 'DEF_ZUZYCIA.csv'
       )
    );
--------------------------------------------------------
--  DDL for Table STG_MATERIAL
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_MATERIAL" 
   (	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"KOSZT_JEDN" NUMBER, 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_MATERIAL_D
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_MATERIAL_D" 
   (	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"KOSZT_JEDN" NUMBER, 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_MATERIAL_EXT
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_MATERIAL_EXT" 
   (	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"KOSZT_JEDN" NUMBER, 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXTERNAL_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
        (
        ID_MATERIALU,NAZWA_MATERIALU,JEDNOSTKA,KOSZT_JEDN,ZRODLO_DANYCH,NUMER_PRZYROSTU
        )
        )
      LOCATION
       ( 'MATERIAL.csv'
       )
    );
--------------------------------------------------------
--  DDL for Table STG_PRACA
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_PRACA" 
   (	"ID_PRACY" NUMBER, 
	"IMIE_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"NAZWISKO_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ILOSC_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_PRACA_D
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_PRACA_D" 
   (	"ID_PRACY" NUMBER, 
	"IMIE_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"NAZWISKO_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ILOSC_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_PRACA_EXT
--------------------------------------------------------

  CREATE TABLE "HD2018"."STG_PRACA_EXT" 
   (	"ID_PRACY" NUMBER, 
	"IMIE_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"NAZWISKO_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ILOSC_MATERIALU" VARCHAR2(20 BYTE), 
	"ZRODLO_DANYCH" NUMBER, 
	"NUMER_PRZYROSTU" NUMBER
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXTERNAL_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL
        (
        ID_PRACY,IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,PESEL_PRACOWNIKA,DP_PRACY DATE 'YYYY-MM-DD HH24:MI:SS',DZ_PRACY DATE 'YYYY-MM-DD HH24:MI:SS',NAZWA_PRACY,KWOTA_PRACOWNIK,ILOSC,NAZWA_MATERIALU,ILOSC_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU
        )
        )
      LOCATION
       ( 'PRACA.csv'
       )
    );
--------------------------------------------------------
--  DDL for Table TMP_DEF_PRACY
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_DEF_PRACY" 
   (	"ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"NORMA_MIN_H" NUMBER, 
	"NORMA_MAX_H" NUMBER, 
	"KOSZT_JEDN_PRACY" NUMBER,
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER	
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_DEF_ZUZYCIA
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_DEF_ZUZYCIA" 
   (	"ID_DEF_ZUZYCIA" VARCHAR2(20 BYTE), 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"CHD_ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE),
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_DEF_ZUZYCIA_BAD
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_DEF_ZUZYCIA_BAD" 
   (	"ID_DEF_ZUZYCIA" VARCHAR2(20 BYTE), 
	"NORMA_MIN_JEDN" NUMBER, 
	"NORMA_MAX_JEDN" NUMBER, 
	"CHD_ID_DEF_PRACY" NUMBER, 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"CHD_ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ERR1" NUMBER, 
	"LICZBA_PROCESOWAN" NUMBER DEFAULT 1, 
	"DATA_DODANIA" DATE DEFAULT sysdate, 
	"ERR2" NUMBER, 
	"TMP_ID_DEF_ZUZYCIA" NUMBER,
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
 

   COMMENT ON COLUMN "HD2018"."TMP_DEF_ZUZYCIA_BAD"."ERR1" IS 'BRAK DEF_PRACY W SLOWNIKU';
 
   COMMENT ON COLUMN "HD2018"."TMP_DEF_ZUZYCIA_BAD"."ERR2" IS 'BRAK MATERIALU W SLOWNIKU';
--------------------------------------------------------
--  DDL for Table TMP_MATERIAL
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_MATERIAL" 
   (	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(100 BYTE), 
	"JEDNOSTKA" VARCHAR2(100 BYTE), 
	"KOSZT_JEDN" NUMBER,
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_PRACA
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_PRACA" 
   (	"ID_PRACY" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"CHD_ID_DEF_PRACY" VARCHAR2(20 BYTE), 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"CHD_ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ILOSC_MATERIALU" NUMBER,
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_PRACA_BAD
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_PRACA_BAD" 
   (	"ID_PRACY" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"DP_PRACY" DATE, 
	"DZ_PRACY" DATE, 
	"CHD_ID_DEF_PRACY" VARCHAR2(20 BYTE), 
	"NAZWA_PRACY" VARCHAR2(20 BYTE), 
	"KWOTA_PRACOWNIK" NUMBER, 
	"ILOSC" NUMBER, 
	"CHD_ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(20 BYTE), 
	"ILOSC_MATERIALU" NUMBER, 
	"ERR1" NUMBER, 
	"ERR2" NUMBER, 
	"ILOSC_PROCESOWAN" NUMBER, 
	"DATA_DODANIA" DATE DEFAULT sysdate, 
	"TMP_ID_PRACY" NUMBER,
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;
 

   COMMENT ON COLUMN "HD2018"."TMP_PRACA_BAD"."ERR1" IS 'BRAK DEF_PRACY';
 
   COMMENT ON COLUMN "HD2018"."TMP_PRACA_BAD"."ERR2" IS 'BRAK MATERIALU';
--------------------------------------------------------
--  DDL for Table TMP_PRACOWNIK
--------------------------------------------------------

  CREATE TABLE "HD2018"."TMP_PRACOWNIK" 
   (	"IMIE_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"NAZWISKO_PRACOWNIKA" VARCHAR2(20 BYTE), 
	"PESEL_PRACOWNIKA" VARCHAR2(20 BYTE),
	"ZRODLO_DANYCH" NUMBER, 
	"USUNIETY" NUMBER
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
  TABLESPACE "DATA" ;

Insert into HD2018.META_DATA (NAZWA,NUMER_OST_ZAL_PRZYROSTU) values ('MATERIAL',null);
Insert into HD2018.META_DATA (NAZWA,NUMER_OST_ZAL_PRZYROSTU) values ('PRACOWNIK',null);
Insert into HD2018.META_DATA (NAZWA,NUMER_OST_ZAL_PRZYROSTU) values ('DEF_ZUZYCIA',null);
Insert into HD2018.META_DATA (NAZWA,NUMER_OST_ZAL_PRZYROSTU) values ('PRACA',null);
Insert into HD2018.META_DATA (NAZWA,NUMER_OST_ZAL_PRZYROSTU) values ('DEF_PRACY',null);


--------------------------------
--Sciezka do CSV----------------
--------------------------------
CREATE OR REPLACE DIRECTORY EXTERNAL_DIR AS 'C:\Users\MatexN\Desktop\HD_FINAL\Source\CSV';


--------------------------------------------------------
--  File created - środa-maja-30-2018   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence STG_DEF_PRACY_D_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_DEF_PRACY_D_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STG_DEF_PRACY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_DEF_PRACY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STG_DEF_PRACY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "STG_DEF_ZUZYCIA_D_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STG_DEF_ZUZYCIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_DEF_ZUZYCIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence STG_MATERIAL_D_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_MATERIAL_D_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STG_MATERIAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_MATERIAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence STG_PRACA_D_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_PRACA_D_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STG_PRACA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STG_PRACA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence TMP_DEF_ZUZYCIA_BAD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TMP_DEF_ZUZYCIA_BAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TMP_PRACA_BAD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TMP_PRACA_BAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   
--------------------------------------------------------
--  DDL for Sequence TMP_DEF_PRACY
--------------------------------------------------------

	CREATE SEQUENCE  "TMP_DEF_PRACY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	
--------------------------------------------------------
--  DDL for Sequence TMP_DEF_ZUZYCIA
--------------------------------------------------------

	CREATE SEQUENCE  "TMP_DEF_ZUZYCIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	
--------------------------------------------------------
--  DDL for Sequence TMP_MATERIAL
--------------------------------------------------------

	CREATE SEQUENCE  "TMP_MATERIAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	
--------------------------------------------------------
--  DDL for Sequence TMP_PRACA
--------------------------------------------------------

	CREATE SEQUENCE  "TMP_PRACA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence TMP_PRACOWNIK
--------------------------------------------------------

	CREATE SEQUENCE  "TMP_PRACOWNIK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------
--PROCEDURA LOAD_CSV------------
--------------------------------
create or replace PROCEDURE "LOAD_FROM_CSV" AS 
BEGIN    

    EXECUTE IMMEDIATE 'ALTER TABLE STG_DEF_PRACY_EXT LOCATION (''DEF_PRACY.csv'')';

    EXECUTE IMMEDIATE 'ALTER TABLE STG_DEF_ZUZYCIA_EXT LOCATION (''DEF_ZUZYCIA.csv'')';

    EXECUTE IMMEDIATE 'ALTER TABLE STG_MATERIAL_EXT LOCATION (''MATERIAL.csv'')';

    EXECUTE IMMEDIATE 'ALTER TABLE STG_PRACA_EXT LOCATION (''PRACA.csv'')';

    INSERT INTO STG_DEF_PRACY (ID_DEF_PRACY,NAZWA_PRACY,JEDNOSTKA,NORMA_MIN_H,NORMA_MAX_H,KOSZT_JEDN_PRACY,ZRODLO_DANYCH,NUMER_PRZYROSTU)
    SELECT ID_DEF_PRACY,NAZWA_PRACY,JEDNOSTKA,NORMA_MIN_H,NORMA_MAX_H,KOSZT_JEDN_PRACY,ZRODLO_DANYCH,NUMER_PRZYROSTU
    FROM STG_DEF_PRACY_EXT;

    INSERT INTO STG_DEF_ZUZYCIA (ID_DEF_ZUZYCIA,NORMA_MIN_JEDN,NORMA_MAX_JEDN,NAZWA_PRACY,NAZWA_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU)
    SELECT ID_DEF_ZUZYCIA,NORMA_MIN_JEDN,NORMA_MAX_JEDN,NAZWA_PRACY,NAZWA_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU
    FROM STG_DEF_ZUZYCIA_EXT;

    INSERT INTO STG_MATERIAL (ID_MATERIALU,NAZWA_MATERIALU,JEDNOSTKA,KOSZT_JEDN,ZRODLO_DANYCH,NUMER_PRZYROSTU)
    SELECT ID_MATERIALU,NAZWA_MATERIALU,JEDNOSTKA,KOSZT_JEDN,ZRODLO_DANYCH,NUMER_PRZYROSTU
    FROM STG_MATERIAL_EXT;

    INSERT INTO STG_PRACA (ID_PRACY,IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,PESEL_PRACOWNIKA,DP_PRACY,DZ_PRACY,NAZWA_PRACY,KWOTA_PRACOWNIK,ILOSC,NAZWA_MATERIALU,ILOSC_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU)
    SELECT ID_PRACY,IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,PESEL_PRACOWNIKA,DP_PRACY,DZ_PRACY,NAZWA_PRACY,KWOTA_PRACOWNIK,ILOSC,NAZWA_MATERIALU,ILOSC_MATERIALU,ZRODLO_DANYCH,NUMER_PRZYROSTU
    FROM STG_PRACA_EXT;

END LOAD_FROM_CSV;

--------------------------------------------------------
--  DDL for Procedure CLEAR_DATA
--------------------------------------------------------

  CREATE OR REPLACE PROCEDURE "CLEAR_DATA" AS 
BEGIN
  DELETE FROM CHD_PRACA;
  DELETE FROM CHD_DEF_ZUZYCIA;
  DELETE FROM CHD_DEF_PRACY;
  DELETE FROM CHD_MATERIAL;
  DELETE FROM CHD_PRACOWNIK;
  DELETE FROM META_DATA;
  DELETE FROM STG_DEF_PRACY;
  DELETE FROM STG_DEF_PRACY_D;
  DELETE FROM STG_DEF_ZUZYCIA;
  DELETE FROM STG_DEF_ZUZYCIA_D;
  DELETE FROM STG_MATERIAL;
  DELETE FROM STG_MATERIAL_D;
  DELETE FROM STG_PRACA;
  DELETE FROM STG_PRACA_D;
  DELETE FROM TMP_DEF_ZUZYCIA_BAD;
  DELETE FROM TMP_PRACA_BAD;
  
  INSERT INTO META_DATA(NAZWA,NUMER_OST_ZAL_PRZYROSTU,NUMER_OST_PRZYROSTU) VALUES('MATERIAL',0,0);
  INSERT INTO META_DATA(NAZWA,NUMER_OST_ZAL_PRZYROSTU,NUMER_OST_PRZYROSTU) VALUES('PRACOWNIK',0,0);
  INSERT INTO META_DATA(NAZWA,NUMER_OST_ZAL_PRZYROSTU,NUMER_OST_PRZYROSTU) VALUES('DEF_ZUZYCIA',0,0);
  INSERT INTO META_DATA(NAZWA,NUMER_OST_ZAL_PRZYROSTU,NUMER_OST_PRZYROSTU) VALUES('PRACA',0,0);
  INSERT INTO META_DATA(NAZWA,NUMER_OST_ZAL_PRZYROSTU,NUMER_OST_PRZYROSTU) VALUES('DEF_PRACY',0,0);
  
END CLEAR_DATA;

/


------------------
---LOAD TO TMP----
------------------
create or replace procedure "LOAD_TO_TMP" as
last_increase NUMBER;
BEGIN
SELECT NUMER_OST_PRZYROSTU INTO last_increase FROM META_DATA WHERE NAZWA='MATERIAL';
last_increase := last_increase +1;
FOR rec IN(SELECT ID_MATERIALU, NAZWA_MATERIALU, JEDNOSTKA, KOSZT_JEDN, ZRODLO_DANYCH, USUNIETY FROM STG_MATERIAL WHERE NUMER_PRZYROSTU=last_increase)
LOOP
INSERT INTO TMP_MATERIAL(ID_MATERIALU, NAZWA_MATERIALU, JEDNOSTKA, KOSZT_JEDN, ZRODLO_DANYCH, USUNIETY)
VALUES(rec.ID_MATERIALU, rec.NAZWA_MATERIALU, rec.JEDNOSTKA, rec.KOSZT_JEDN, rec.ZRODLO_DANYCH, rec.USUNIETY);
END LOOP;

FOR rec IN(SELECT ID_DEF_PRACY, NAZWA_PRACY, JEDNOSTKA, NORMA_MIN_H, NORMA_MAX_H, KOSZT_JEDN_PRACY,ZRODLO_DANYCH, USUNIETY FROM STG_DEF_PRACY WHERE NUMER_PRZYROSTU=last_increase)
LOOP
INSERT INTO TMP_DEF_PRACY(ID_DEF_PRACY, NAZWA_PRACY, JEDNOSTKA, NORMA_MIN_H, NORMA_MAX_H, KOSZT_JEDN_PRACY,ZRODLO_DANYCH, USUNIETY)
VALUES(rec.ID_DEF_PRACY, rec.NAZWA_PRACY, rec.JEDNOSTKA, rec.NORMA_MIN_H, rec.NORMA_MAX_H, rec.KOSZT_JEDN_PRACY,rec.ZRODLO_DANYCH, rec.USUNIETY);
END LOOP;

FOR rec IN(SELECT IMIE_PRACOWNIKA, NAZWISKO_PRACOWNIKA, PESEL_PRACOWNIKA, ZRODLO_DANYCH, USUNIETY FROM STG_PRACA WHERE NUMER_PRZYROSTU=last_increase)
LOOP
INSERT INTO TMP_PRACOWNIK(IMIE_PRACOWNIKA, NAZWISKO_PRACOWNIKA, PESEL_PRACOWNIKA, ZRODLO_DANYCH, USUNIETY)
VALUES(rec.IMIE_PRACOWNIKA, rec.NAZWISKO_PRACOWNIKA, rec.PESEL_PRACOWNIKA, rec.ZRODLO_DANYCH, rec.USUNIETY);
END LOOP;

--Tu odpalamy ETL dla tych co dodaliśmy, USUWANIE PRACOWNIKA PO SPRAWDZENIU CZY NIE JEST PRZYPISANY DO ŻADNEJ PRACY WIĘC ODDZIELNA PROCEDURA NA SAMYM KONCU ETL--

-- KOLEJNE ŁADOWANIA PO ETLkach, SZUKANIE ID W TABELACH KLUCZY TYCH DODANYCH--


END;
